stock_portfolio_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock_portfolio_tracker.stock_tracker_users.urls')),
    path('portfilio/', include('stock_portfolio_tracker.stock_tracker_stocks.urls')),
    path('profile/', include('stock_portfolio_tracker.stock_tracker_profiles.urls')),
    path('api/', include('stock_portfolio_tracker.stock_tracker_stocks.urls'))
]

stock_portfolio_tracker/stock_tracker_stocks/models.py
from django.db import models
from stock_portfolio_tracker.stock_tracker_users.models import MyUser


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25, blank=True, null=True)
    last_name = models.CharField(max_length=25, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    created = models.DateField(auto_now=True)

    def __str__(self):
        return f"Profile of {self.user.email}"


class Portfolio(models.Model):
    owner = models.OneToOneField(Profile, on_delete=models.CASCADE)
    stocks = models.ManyToManyField("Stock", through='PortfolioItem')
    realised_pnl = models.FloatField(default=0)
    invested = models.FloatField(default=0, null=True)

    def __str__(self):
        return f"Portfolio of {self.owner.user.email}"


class PortfolioItem(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    stock = models.ForeignKey("Stock", on_delete=models.CASCADE)
    quantity = models.FloatField(default=0)
    average_purchase_price = models.FloatField(default=0)

    def __str__(self):
        return f"{self.stock.symbol} - {self.quantity} shares"


class Stock(models.Model):
    symbol = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100)
    price = models.FloatField(default=0)

    def __str__(self):
        return self.symbol


class Sale(models.Model):
    initiator = models.ForeignKey(Profile, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    quantity_sold = models.FloatField(default=0)
    sale_price = models.FloatField(default=0)

    def __str__(self):
        return f"Sale of {self.stock} by {self.initiator}"


class Buy(models.Model):
    initiator = models.ForeignKey(Profile, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    quantity_bought = models.FloatField(default=0)
    buy_price = models.FloatField(default=0)

    def __str__(self):
        return f"Buy of {self.stock} by {self.initiator}"

templates/portfolio/add_stock.html
{% extends 'base.html' %}
{% block page_content %}
<main>
    <section class="heading wrapper hidden">
        <h2>Add Stock to Portfolio</h2>
    </section>
    <section class="bottom hidden">
        <form method="post" class="wrapper orders">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Stock</button>
        </form>
    </section>
</main>
{% endblock %}

templates/portfolio/buy.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
<main>
    <section class="heading wrapper hidden">
        <h2>Buy {{ portfolio_item.stock.name }}</h2>
    </section>
    <section class="bottom hidden">
        <form method="post" class="wrapper orders col">
            {% csrf_token %}
            <p class="symbol paragraph">
                <span class="portfolio value">{{ portfolio_item.stock.symbol }}</span>
            </p>
            {{ form.as_p }}
            <button type="button" id="request-price" class="btn btn-primary"> Show Current Price</button>
            <button type="submit" class="btn btn-primary">Confirm Buy</button>
        </form>
    </section>
    <script type="module" src="{% static 'js/refreshPrice.js' %}"></script>
</main>
{% endblock %}

templates/portfolio/buys_history.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
<main>
    <section class="history-top wrapper actions hidden">
        <h2>Portfolio Buys</h2>
        <p>Realised P&L: &dollar;{{ realised_pnl }}</p>
        <a href="{% url 'sales_details' profile_pk portfolio_pk %}" class="custom a">Sales History</a>
        <a href="{% url 'portfolio_details' portfolio_pk%}" class="custom a">Portfolio</a>
    </section>
    <section class="history-bottom wrapper actions hidden">
        {% for buy in object_list %}
            <div class="history-inner wrapper actions">
                <div class="history-inner-left wrapper actions">
                    <p>Ticker Symbol: <span class="portfolio value">{{ buy.stock.symbol }}</span></p>
                    <p>Name: <span class="portfolio value">{{ buy.stock.name }}</span></p>
                    <p>Date: <span class="portfolio value">{{ buy.date }}</span></p>
                </div>
                <div class="history-inner-right wrapper actions">
                    <p>Shares: <span class="portfolio value">{{ buy.quantity_bought }}</span></p>
                    <p>Price: <span class="portfolio value">&dollar;{{ buy.buy_price }}</span></p>
                </div>
            </div>
        {% empty%}
            <p class="warning hidden" style="color: #cccccc">No buys recorded!</p>
        {% endfor %}
    </section>
</main>
{% endblock %}

templates/portfolio/details.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
<main>
    <section class="portfolio top wrapper hidden">
        <p class="number">Invested: <span class="portfolio number">&dollar;{{ object.invested }}</span></p>
        <p class="number">Realised P&L: <span class="portfolio number">&dollar;{{ object.realised_pnl }}</span></p>
        <div class="wrapper history btns">
            <a href="{% url 'sales_details' object.owner_id object.pk %}" class="custom a">Sales History</a>
            <a href="{% url 'buys_details' object.owner_id object.pk %}" class="custom a">Buys History</a>
        </div>
    </section>
    <hr>
    <section class="middle-portfolio wrapper hidden">
        <a href="{% url 'add_stock' request.user.profile.portfolio.pk %}" class="custom a">Add New Position</a>
        <a href="{% url 'reset_portfolio' request.user.pk request.user.profile.portfolio.pk %}" class="custom a">Reset Portfolio</a>
    </section>
    <section class="quotes wrapper hidden">
        {% for item in object.portfolioitem_set.all %}
            <div class="investment-container wrapper">
                <div class="investment-row one wrapper">
                    <p class="stock symbol">{{ item.stock.symbol }}</p>
                    <p id="{{ item.stock.symbol }} avg_price" class="number center">Average Price: &dollar;{{ item.average_purchase_price }}</p>
                    <p id="{{ item.stock.symbol }} price" class="number">Current Price: &dollar;<span class="{{ item.stock.symbol }} current-price number"></span>
                    </p>
                </div>
                <div class="investment-row two wrapper">
                    <p class="lower">{{ item.stock.name }}</p>
                    <p id="{{ item.stock.symbol }} shares" class="number center lower">Shares: {{ item.quantity }}</p>
                    <p id="pnl text" class="number">P&L:
                        <span id="{{ item.stock.symbol }} pnl-percentage" class="{{ item.stock.symbol }} current-pnl number">-%</span>
                    </p>
                </div>
                <div class="refresh-btns wrapper">
                    <div class="refresh-btns-nested wrapper">
                        <button id="{{ item.stock.symbol }}btn" class="refresh btn btn-primary">Refresh Price</button>
                        <button id="{{ item.stock.symbol }} pnl-btn" class="{{ item.stock.symbol }} pnl btn btn-primary">Calculate P&L</button>
                    </div>
                </div>
                <div class="investment-btns wrapper">
                    <a href="{% url 'buy_stock' object.pk item.stock.symbol %}" class="btn btn-primary">Buy</a>
                    <a href="{% url 'sell_stock' object.pk item.stock.symbol %}" class="btn btn-primary">Sell</a>
                    <a href="{% url 'remove_stock' object.pk item.stock.symbol %}" class="btn btn-primary">Remove</a>
                </div>
            </div>
        {% empty %}
            <div style="display: flex; align-items: center; justify-content: center; flex-direction: column; gap: 20px" class="hidden">
                <p class="stock symbol">No investments!</p>
                <a href="{% url 'add_stock' request.user.profile.portfolio.pk %}" class="custom a">Add New Position</a>
            </div>
        {% endfor %}
    </section>
</main>
    <script type="module" src="{% static 'js/refreshQuotes.js' %}"></script>
    <script type="module" src="{% static 'js/calculatePnl.js' %}"></script>
{% endblock %}type="module"

templates/portfolio/not_existing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>404</title>
     <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
    <link rel="stylesheet" href="{% static 'css/404.css' %}">
</head>
<body>
<main>
    <section class="error wrapper hidden">
        <p class="warning">We do not support this stock</p>
        <a href="{% url 'homepage' %}" class="custom a">Go Home</a>
    </section>
</main>
</body>
</html>

templates/portfolio/remove.html
{% extends 'base.html' %}
{% block page_content %}
<main>
    <section class="heading wrapper col hidden">
        <h2>Remove {{ object.stock.name }}</h2>
        <p class="warning">Your position in {{ object.stock.name }} will be removed. No profits or losses will be recorded!</p>
    </section>
    <section class="bottom hidden">
        <form method="post" class="wrapper orders">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Confirm</button>
        </form>
    </section>
</main>
{% endblock %}

templates/portfolio/reset.html
{% extends 'base.html' %}
{% block page_content %}
<main>
    <div class="wrapper portfolio info hidden">
        <h2>Reset Portfolio</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>
{% endblock %}

templates/portfolio/sales_history.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
<main>
    <section class="history-top wrapper actions hidden">
        <h2>Portfolio Sales</h2>
        <p>Realised P&L: &dollar;{{ realised_pnl }}</p>
        <a href="{% url 'buys_details' profile_pk portfolio_pk %}" class="custom a">Buys History</a>
        <a href="{% url 'portfolio_details' portfolio_pk%}" class="custom a">Portfolio</a>
    </section>
    <section class="history-bottom wrapper actions hidden">
        {% for sale in object_list %}
            <div class="history-inner wrapper actions">
                <div class="history-inner-left wrapper actions">
                    <p>Ticker Symbol: <span class="portfolio value">{{ sale.stock.symbol }}</span></p>
                    <p>Name: <span class="portfolio value">{{ sale.stock.name }}</span></p>
                    <p>Date: <span class="portfolio value">{{ sale.date }}</span></p>
                </div>
                <div class="history-inner-right wrapper actions">
                    <p>Shares: <span class="portfolio value">{{ sale.quantity_sold }}</span></p>
                    <p>Price: <span class="portfolio value">&dollar;{{ sale.sale_price }}</span></p>
                </div>
            </div>
        {% empty%}
            <p class="warning" style="color: #cccccc">No sales recorded!</p>
        {% endfor %}
    </section>
</main>
{% endblock %}

templates/portfolio/sell.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
<main>
    <section class="heading wrapper col hidden">
        <h2>Sell {{ portfolio_item.stock.name }}</h2>
        <p class="warning">
            Your position in
            {{ portfolio_item.stock.symbol }}
            will be reduced or sold completely.
            The profits or losses will be recorded!
        </p>
        </section>
    <section class="bottom hidden">
        <form method="post" class="wrapper orders col">
            {% csrf_token %}
              <p class="symbol paragraph">
                  <span class="portfolio value">{{ portfolio_item.stock.symbol }}</span>
              </p>
            <p>Available Shares:
                <span class="portfolio value number">{{ portfolio_item.quantity }}</span>
            </p>
            <p>Average Purchase Price:
                <span class="portfolio value number">&dollar;{{ portfolio_item.average_purchase_price }}</span>
            </p>
            {{ form.as_p }}
            <button type="button" id="request-price" class="btn btn-primary"> Show Current Price</button>
            <button type="submit" class="btn btn-primary">Confirm Sell</button>
        </form>
    </section>
</main>
<script type="module" src="{% static 'js/refreshPrice.js' %}"></script>
{% endblock %}